driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[ruby-ng::default]
